# Generated by Django 3.2.13 on 2022-07-02 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название принтера')),
                ('api_key', models.CharField(help_text='принимает уникальные значения, по нему однозначно определяется принтер', max_length=250, unique=True, verbose_name='ключ доступа к API')),
                ('check_type', models.CharField(choices=[('KN', 'Кухня'), ('CL', 'Клиент')], default='KN', max_length=2, verbose_name='тип чека которые печатает принтер')),
                ('point_id', models.IntegerField(verbose_name='точка к которой привязан принтер')),
            ],
            options={
                'verbose_name': 'Принтер',
                'verbose_name_plural': 'Принтеры',
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('KN', 'Кухня'), ('CL', 'Клиент')], default='KN', max_length=2, verbose_name='тип чека')),
                ('order', models.JSONField(verbose_name='информация о заказе')),
                ('status', models.CharField(choices=[('NW', 'Новый'), ('RE', 'Обработанный'), ('PR', 'Распечатанный')], default='NW', max_length=2, verbose_name='статус чека')),
                ('printer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='check_api.printer')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
            },
        ),
    ]
