# Generated by Django 3.2.13 on 2022-07-03 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('check_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='media/pdf/', verbose_name='созданный PDF-файл'),
        ),
        migrations.AlterField(
            model_name='check',
            name='printer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checks', to='check_api.printer'),
        ),
    ]
