# Generated by Django 3.2.13 on 2022-07-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_api', '0002_auto_20220703_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='check_type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='check',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdf/', verbose_name='созданный PDF-файл'),
        ),
    ]
